const assert = require('assert');
assert.fail(1, 2, 'This is an error', '>'); 